### ISSUE TITLE
Unable to retrieve the "Brightness" characteristic

### ISSUE THREAD

**Issue by kskaret** [amlinger/homebridge-telldus-tdtool#23]
This occurs when using dimmers.
It's fully possible to set the brightness characteristic, but when the state is read, only 'undefined' seems to be returned.

I found the following in homebridge.err:

Thu, 22 Sep 2016 10:34:49 GMT Accessory [Homebridge Raspberry] Registering Characteristic "Brightness" for events
Thu, 22 Sep 2016 10:34:49 GMT EventedHTTPServer [::ffff:10.0.1.32] HTTP Response is finished
Thu, 22 Sep 2016 10:34:50 GMT EventedHTTPServer [::ffff:10.0.1.32] HTTP request: /characteristics?id=11.9,11.8,17.9,12.8,10.8,13.8,15.9,15.8
Thu, 22 Sep 2016 10:34:50 GMT HAPServer [C1:12:31:E3:CE:30] HAP Request: GET /characteristics?id=11.9,11.8,17.9,12.8,10.8,13.8,15.9,15.8
Thu, 22 Sep 2016 10:34:50 GMT Accessory [Homebridge Raspberry] Getting value for Characteristic "Brightness"
Thu, 22 Sep 2016 10:34:50 GMT Accessory [Homebridge Raspberry] Got Characteristic "Brightness" value: undefined
Thu, 22 Sep 2016 10:34:50 GMT Accessory [Homebridge Raspberry] Error getting value for Characteristic "Brightness": undefined

**Comment by kskaret** [comment]
Hm, I see you have done a lot of refactoring. Maybe it has been sorted out now allready?

**Comment by kskaret** [comment]
No forget about this. I just tried the latest master branch, and now it seems to work fine. Cheers :)

**Comment by amlinger** [comment]
Hi @kskaret!

Yes, a lot of refactoring has been done done the old accessory implementation simply didn't scale when adding new accessories. In this process, the brightness should've been somewhat fixed.

A issue still remain though, since reading brightness is based on lastsentcommand from tdtool, and reading the current value of dimmer does not work. I expect to address that in a future patch.

Cheers!
