### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jamesbryer** [amlinger/homebridge-telldus-tdtool#56]
Hi,

I recently got some help setting up td tool on my macbook pro however this became annoying as i need my macbook running 24/7 and the tellstick being attached gets in the way

I have set up homebridge on my Windows 10 Pro server, installed telldus centre (including telldus core if the internet is correct), got the parser installed, set up my config.json and the tellstick.config file however when I run homebridge no devices load. Also when I run tdtool --list-devices i get the error

tdtool --list-devices
tdtool : The term 'tdtool' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ tdtool --list-devices
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (tdtool:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I'm pretty  sure everything is set up correctly as I did exactly the same as on my macbook (except using the different file locations due to differences between MacOS and windows) 

Has anyone set up the tellstick on windows or are we all running Unix based OS's? I would run this on my Raspberry Pi however all the sources for telldus-core appear to be offline :( 

Thanks very much!

**Comment by jamesbryer** [comment]
Don't worry! I installed a copy of Ubuntu on my server and got everything up and running! I would be interested to see if anyone gets it running on Windows though...

**Comment by amlinger** [comment]
Hi @jamesbryer!

First off, sorry for the late reply to this.

Personally, I'm running it on my RaspberryPi. I've heard recently that sources for tdtool are removed in the package manager, which is very unfortunate.

Tdtool is needed to run this, and as far as I can tell it does not appear to be present on your Windows system. I'm afraid I'm not very familiar with how it runs on Windows, it's been several years since had a Windows machine. I'm very interested in case you get it working, and if you could share instructions or any errors you encounter along the way, I'd be very grateful.

As for installing Telldus core on Linux, such as on RaspberryPi, the source seem to still live here: http://developer.telldus.com/wiki/TellStickInstallationSource

I have yet to have tried this, so I can't really account for how well it works on a RaspberryPi.

I hope this helps, let me know you have any more questions.

**Comment by jamesbryer** [comment]
No worries for the late reply! 

I did work out it was an issue with TDTool, after uninstalling and reinstalling TelldusCentre (making sure I checked the box for development files) I retried it but same issue.. I looked in the Telldus program files and tdtool did appear to be there but I could not for the life of me get it to run (tdtool --list-devices and tdtool --version did not yield any results). I tried many things but to no avail. I think for most people it's just cheaper, easier and better to run Homebridge on a RPi or Linux based server. No problem though as I had planned on moving to Linux on my server anyway due to its far more stable performance. 

Thanks for all your help and for creating a great tool!
